name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win32, linux] # Plataformas a construir

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine64 wine32

    - name: Install dependencies
      run: |
        npm install

    - name: Cache Electron builder dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-

    - name: Build for Windows
      if: matrix.platform == 'win32'
      run: npm run dist:win
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: npm run dist:linux

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ElectronApp-${{ matrix.platform }}
        path: dist/
